;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple
;; cursors.

(setq mc/cmds-to-run-for-all
      '(
        LaTeX-insert-left-brace
        TeX-insert-backslash
        ace-jump-mode
        ace-jump-move
        autopair-insert-opening
        autopair-insert-or-skip-quote
        autopair-skip-close-maybe
        beginning-of-buffer
        c-electric-colon
        c-electric-delete-forward
        c-electric-paren
        c-electric-semi&comma
        comment-dwim
        dabbrev-expand
        delete-indentation
        electric-newline-and-maybe-indent
        end-of-buffer
        ess-smart-S-assign
        ess-yank
        fill-paragraph
        indent-new-comment-line
        keyboard-quit
        kill-region
        markdown-exdent-or-delete
        matlab-electric-comment
        matlab-justify-line
        matlab-linefeed
        message-beginning-of-line
        org-beginning-of-line
        org-delete-char
        org-end-of-line
        org-fill-paragraph
        org-force-self-insert
        org-kill-line
        org-return-indent
        org-self-insert-command
        orgtbl-hijacker-command-102
        orgtbl-hijacker-command-109
        orgtbl-self-insert-command
        python-backspace
        python-electric-colon
        reindent-then-newline-and-indent
        smex
        sp--self-insert-command
        sp-remove-active-pair-overlay
        swiper
        tex-handle-newline
        undefined
        whole-line-or-region-kill-region
        whole-line-or-region-kill-ring-save
        whole-line-or-region-yank
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        c-electric-star
        counsel-M-x
        handle-switch-frame
        ido-find-file
        ido-switch-buffer
        ido-write-file
        indent-for-tab-command
        kmacro-end-macro
        occur-mode-goto-occurrence
        scroll-bar-toolkit-scroll
        text-scale-decrease
        text-scale-increase
        ))
