;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple
;; cursors.

(setq mc/cmds-to-run-for-all
      '(
        TeX-insert-backslash
        ace-jump-mode
        ace-jump-move
        autopair-insert-opening
        autopair-insert-or-skip-quote
        autopair-skip-close-maybe
        beginning-of-buffer
        c-electric-colon
        c-electric-delete-forward
        c-electric-paren
        c-electric-semi&comma
        dabbrev-expand
        end-of-buffer
        ess-smart-S-assign
        ess-yank
        kill-region
        matlab-electric-comment
        matlab-justify-line
        matlab-linefeed
        org-beginning-of-line
        org-end-of-line
        org-force-self-insert
        org-kill-line
        org-return-indent
        org-self-insert-command
        python-backspace
        python-electric-colon
        smex
        sp--self-insert-command
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        c-electric-star
        handle-switch-frame
        ido-find-file
        ido-switch-buffer
        ido-write-file
        scroll-bar-toolkit-scroll
        text-scale-decrease
        text-scale-increase
        ))
