;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple
;; cursors.

(setq mc/cmds-to-run-for-all
      '(
        ace-jump-mode
        ace-jump-move
        autopair-insert-opening
        autopair-insert-or-skip-quote
        autopair-newline
        autopair-skip-close-maybe
        count-words-region
        dired-toggle-read-only
        ess-smart-underscore
        kill-region
        org-beginning-of-line
        org-end-of-line
        org-self-insert-command
        reindent-then-newline-and-indent
        smex
        undefined
        wdired-finish-edit
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        ido-find-file
        ))
